# 网站主要配置
site_name: 追光小站        # 网站标题，显示在浏览器标签页和导航栏
site_author: Sheng            # 网站作者，用于元数据
site_url: https://shengwq.github.io/ # 网站的 canonical URL，用于 SEO 和社交分享
site_description: Sheng的个人网站 # 网站描述，用于搜索引擎元数据

# 代码仓库信息 (可选，用于在网站上显示仓库链接)
repo_url: https://github.com/Shengwq/Shengwq.github.io.git # 仓库的 URL
repo_name: My-repo        # 在网站上显示的仓库名称

# 版权信息，显示在页面底部
# copyright: copyright © 2026 ShengWenQiang. All rights reserved.
copyright: Copyright &copy; 2026 Sheng

# 主题配置
theme:
  name: material # 使用 Material for MkDocs 主题
  custom_dir: overrides # 指定自定义模板目录

  # 亮暗色模式切换配置（调色板）
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=colo
  palette:
    # 浅色方案
    - scheme: default          # 浅色
      primary: white          # 主色调
      accent: indigo           # 强调色（如链接、按钮）
      toggle:
        icon: material/brightness-7   # 浅色模式下显示的图标（太阳）
        name: Switch to dark mode     # 鼠标悬停时显示的提示文字
    # 深色方案
    - scheme: slate            # 深色
      primary: black         # 主色调
      accent: cyan
      toggle:
        icon: material/brightness-4   # 深色模式下显示的图标（月亮）
        name: Switch to light mode    # 点击后切换到浅色模式

  # 主题功能特性列表
  features:
    - navigation.tabs          # 启用顶部选项卡式导航（位于页面顶端）
    - navigation.top           # 添加“返回顶部”按钮，滚动到一定位置后出现
    - navigation.indexes       # 允许目录本身有 index 页
    - search.highlight         # 搜索结果中高亮显示匹配的关键词

  # 图标配置
  icon:
    logo: material/github         # 网站 Logo 使用 Material 图标库中的 GitHub 图标
  favicon: img/favicon.jpg 
  language: zh

markdown_extensions:
  - attr_list  # 允许为Markdown元素添加属性，比如给图片加CSS类名
  - md_in_html # 允许在HTML块中使用Markdown语法
extra_css:
  - extra.css ##不需要添加前置目录，自动指向overrides目录
extra_javascript:
  - js/falling.js   #落叶
  
# 导航栏配置
# 定义网站的页面结构和导航顺序
nav:
  - Home: index.md
  - 技术笔记:
    - 概览: 学习笔记/index.md
    - 机械设计: 
      - 未来方向: 学习笔记/机械/未来方向.md
      - 三维建模: 学习笔记/机械/SolidWorks.md
    - PLC: 学习笔记/PLC/PLC学习笔记.md
    - 嵌入式: 学习笔记/嵌入式/FreeRTOS入门培训.md
    - 杂七杂八: 学习笔记/杂七杂八/mkdocs笔记.md
  - 思考: 
    - 概览: 思考/index.md
    - “乖孩子”误区: 思考/乖孩子误区.md
    - 关于花钱: 思考/关于花钱.md
  - About: 
    - 关于本站: about/关于本站.md
    - 更新日志: about/更新日志.md